routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProduksController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\JasaPengirimanController;
use App\Http\Controllers\VouchersController;
use App\Http\Controllers\OrdersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin')->group(function () {
        Route::get('/get-penjualan', [App\Http\Controllers\DashboardAdminController::class, 'getPenjualan'])->name('get-penjualan');
        Route::get('/get-penjualan-bulan', [App\Http\Controllers\DashboardAdminController::class, 'getPenjualanBulan'])->name('get-penjualan-bulan');
        Route::resource('/dashboard', DashboardAdminController::class);
        Route::resource('/customer', UserController::class);
        Route::prefix('produk')->group(function () {
            Route::resource('/product', ProduksController::class);
            Route::resource('/kategori', CategoriesController::class);
        });
        Route::resource('/jasa-pengiriman',JasaPengirimanController::class);
        Route::resource('/order', OrdersController::class);
        Route::resource('/company', CompanyController::class);
        Route::resource('/blog', BlogsController::class);
        Route::post('/dashboard-admin', [App\Http\Controllers\DashboardAdminController::class, 'destroyAdmin'])->name('dashboard.destroyAdmin');
        Route::resource('/voucher',VouchersController::class);
        Route::get('/page_confirm_payment/{id}',[App\Http\Controllers\OrdersController::class, 'page_confirm_payment'])->name('pageConfirmPayment');
        Route::get('/page_confirm_pengiriman/{id}',[App\Http\Controllers\OrdersController::class, 'page_confirm_pengiriman'])->name('pageConfirmPengiriman');
        Route::put('/confirm_payment/{id}',[App\Http\Controllers\OrdersController::class, 'confirm_payment'])->name('confirmPayment');
        Route::put('/confirm_pengiriman/{id}',[App\Http\Controllers\OrdersController::class, 'confirm_pengiriman'])->name('confirmPengiriman');
        Route::post('/confirm_order/{id}',[App\Http\Controllers\OrdersController::class, 'confirm_order'])->name('confirmOrder');
        Route::get('/order-export-excel', [App\Http\Controllers\OrdersController::class, 'export'])->name('orderExcel');

    });
});


Route::group(['middleware' => ['company']], function () {
    Auth::routes();

    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/form-login', [App\Http\Controllers\HomeController::class, 'login'])->name('form.login.user');
    Route::get('/form-register', [App\Http\Controllers\HomeController::class, 'register'])->name('form.register.user');
    Route::post('/register-user', [App\Http\Controllers\HomeController::class, 'registerUser'])->name('register.user');
    Route::get('/profile-user', [App\Http\Controllers\HomeController::class, 'profileUser'])->name('profile.user');
    Route::get('/list-order', [App\Http\Controllers\HomeController::class, 'listOrderUser'])->name('listorder.user');
    Route::put('/ubah-profile/{id}', [App\Http\Controllers\HomeController::class, 'ubahProfile'])->name('ubah.profile');
    Route::put('/ubah-password-user/{id}', [App\Http\Controllers\HomeController::class, 'ubahPasswordUser'])->name('ubah.passwordUser');

    Route::get('/detail-order/{id}',[App\Http\Controllers\HomeController::class, 'orderDetailUser'])->name('detailOrder.edit');
    Route::put('/pembayaran-order/{id}',[App\Http\Controllers\HomeController::class, 'konfirmasiOrder'])->name('detailOrder.pembayaran');

    Route::get('/semua-produk', [App\Http\Controllers\HomeController::class, 'shopUser'])->name('shop.user');
    Route::get('/semua-produk/{id}/{slug}', [App\Http\Controllers\HomeController::class, 'detailProduk'])->name('detail.produk');

    Route::get('/get-cart', [App\Http\Controllers\HomeController::class, 'getCart'])->name('get-cart');
    Route::post('/add-cart', [App\Http\Controllers\HomeController::class, 'addCart'])->name('add-cart');
    Route::post('/update-cart', [App\Http\Controllers\HomeController::class, 'updateCart'])->name('update-cart');
    Route::get('/detail-cart', [App\Http\Controllers\HomeController::class, 'detailCart'])->name('detail-cart');
    Route::delete('/delete-cart', [App\Http\Controllers\HomeController::class, 'deleteCart'])->name('delete-cart');

    Route::get('/get-voucher', [App\Http\Controllers\HomeController::class, 'getVoucher'])->name('get-voucher');

    Route::post('/checkout', [App\Http\Controllers\HomeController::class, 'checkout'])->name('checkout');

    Route::get('/address/user', [App\Http\Controllers\HomeController::class, 'addressUser'])->name('address.user');
    Route::get('/address/user/create', [App\Http\Controllers\HomeController::class, 'addressUserCreate'])->name('address.user.create');
    Route::post('/address/user/store', [App\Http\Controllers\HomeController::class, 'addressUserStore'])->name('address.user.store');
    Route::get('/address/user/edit/{id}', [App\Http\Controllers\HomeController::class, 'addressUserEdit'])->name('address.user.edit');
    Route::put('/address/user/update/{id}', [App\Http\Controllers\HomeController::class, 'addressUserUpdate'])->name('address.user.update');
    Route::delete('/address/user/destroy/{id}', [App\Http\Controllers\HomeController::class, 'addressUserDestroy'])->name('address.user.destroy');

    Route::get('/company-profile', [App\Http\Controllers\HomeController::class, 'companySetting'])->name('company-setting');
    Route::get('/blog', [App\Http\Controllers\HomeController::class, 'blogSetting'])->name('blog');
    Route::get('/blog-detail/{id}',[App\Http\Controllers\HomeController::class, 'blogDetail'])->name('blog-detail');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function customers()
    {
        return $this->hasOne(customers::class);
    }

    public function chats()
    {
        return $this->hasMany(chats::class);
    }

    public function notifikasis()
    {
        return $this->hasMany(notifikasis::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\customers;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $user = User::where('role', 'user')
        ->orderBy('created_at','desc');
        if (isset($search) && !empty($search)) {
            $user->where(function ($query) use ($search) {
                $query->where('username', 'like', '%' . $search . '%')
                    ->orWhere('email', 'like', '%' . $search . '%')
                        ->orWhereHas('customers', function ($query2) use ($search){
                            $query2->where('nama_lengkap', 'like', '%' . $search . '%');
                });
            });
        }
        $user = $user->paginate(7);
        return view('admin.user.index', [
            'users' => $user,
            'search' => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validasi = Validator::make($request->all(),[
            'password' => 'confirmed'
        ]);

        if (!$validasi->fails()) {
            try {
                DB::beginTransaction();
                $user = User::find($id);
                $user->username = $request->username;
                $user->email = $request->email;
                $user->password = Hash::make($request->password);
                $user->role = 'user';
                $user->save();

                $customer = customers::where('user_id',$user->id)->first();
                $customer->nama_lengkap = $request->nama_lengkap;
                $customer->telp = $request->telp;
                $customer->tempat_lahir = $request->tempat_lahir;
                $customer->tanggal_lahir = $request->tanggal_lahir;
                if ($request->img_profile) {
                    $gambar = $this->uploadGambar($request->img_profile);
                    $customer->img_profile = $gambar;
                }
                $customer->save();

                DB::commit();
                session()->flash('success','Berhasil Mengubah Data Customer!');
                return redirect()->route('customer.index');
            } catch (\Exception $e) {
                DB::rollback();
                session()->flash('warning','Gagal Mengubah Data Customer!');
                return redirect()->back();
            }
        } else {
            session()->flash('warning','Password Yang Anda Masukkan Tidak Sama!');
            return redirect()->back();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return response()->json([
            'message' => 'Berhasil menghapus data customer!'
        ]);
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Customer
@endsection

@section('content')
  <div class="col-span-12 my-6">
    <div class="d-flex justify-content-between align-items-center">
        <h2 class="text-lg font-medium truncate">Ubah Data Customer</h2>
        <div class="intro-y col-span-12 flex justify-between flex-wrap sm:flex-no-wrap items-center">
            <a href="{{route('customer.index')}}" class="btn btn-secondary"> Kembali </a>
        </div>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
        <form action="{{ route('customer.update',$user->id) }}" method="POST" autocomplete="off" enctype="multipart/form-data">
          @method('PUT')
          @csrf
          <div class="card">
            <div class="card-body">
                <div class="col-lg-12">
                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label class="form-label">Nama Lengkap</label>
                            <input type="text" name="nama_lengkap" class="form-control form-control-sm" placeholder="Masukkan nama lengkap" value="{{$user->customers->nama_lengkap}}" >
                        </div>
                        <div class="col-lg-6">
                            <label class="form-label">Username</label>
                            <input type="text" name="username" class="form-control form-control-sm" placeholder="Masukkan username" value="{{$user->username}}" >
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-lg-6">
                            <label class="form-label">No Telepon</label>
                            <input type="text" name="telp" class="form-control form-control-sm" placeholder="Masukkan no telpon" value="{{$user->customers->telp}}" >
                        </div>
                        <div class="col-lg-6">
                            <label class="form-label">Tempat Lahir</label>
                            <input type="text" name="tempat_lahir" class="form-control form-control-sm" placeholder="Masukkan tempat lahir" value="{{$user->customers->tempat_lahir}}" >
                        </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-lg-12">
                          <label class="form-label">Tanggal Lahir</label>
                          <input type="date" name="tanggal_lahir" class="form-control form-control-sm" placeholder="Masukkan nama kategori" value="{{date('Y-m-d', strtotime($user->customers->tanggal_lahir))}}" >
                      </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-lg-12">
                          <label class="form-label">Gambar</label>
                          <input type="file" name="img_profile" class="form-control form-control-sm bg-white" placeholder="Masukkan nama kategori" value="" >
                          <div class="mt-4">
                            <a class="btn btn-primary fancybox" id="basic-addon2" data-caption="{{$user->username}}" href="{{asset('upload/'.$user->customers->img_profile)}}">Lihat Gambar</a>
                          </div>
                      </div>
                    </div>
                </div>
            </div>
          </div>
          <div class="card">
            <div class="card-body">
                <div class="col-lg-12">
                    <div class="row mb-3">
                        <div class="col-lg-12">
                            <label class="form-label">Email</label>
                            <input type="text" name="email" class="form-control form-control-sm" placeholder="Masukkan nama kategori" value="{{$user->email}}" >
                        </div>
                    </div>
                    <div class="row mb-3">
                      <div class="col-lg-6">
                          <label class="form-label">Password</label>
                          <input type="password" name="password" class="form-control form-control-sm" placeholder="******" value="" >
                      </div>
                      <div class="col-lg-6">
                        <label class="form-label">Konfirmasi Password</label>
                        <input type="password" name="password_confirmation" class="form-control form-control-sm" placeholder="******" value="" >
                    </div>
                    </div>
                </div>
            </div>
          </div>
          <div class="col-span-12 d-flex justify-content-end" >
            <button type="submit" class="btn btn-success"> Simpan </button>
          </div>
        </form>
    </div>
  </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Customer
@endsection

@section('content')
<div class="card">
  <div class="card-body">
    <div class="d-flex align-items-center mb-3">
       <h5 class="mb-0" style="color: #ff8906">Customer Tabel</h5>
    </div>
    <div class="d-flex justify-content-between align-items-center" >
      <form class="position-relative" action="" method="get" >
        <div class="position-absolute top-50 translate-middle-y search-icon px-3"><ion-icon name="search-sharp"></ion-icon></div>
        <input id="search-input" class="form-control  form-control-sm ps-5" value="{{$search}}" type="text" name="search" autocomplete="off" placeholder="search">
      </form>
    </div>
    <div id="indikator-loading-data" class="d-none d-flex justify-content-center align-items-center gap-2">
      <div id="loading-icon" class="spinner-border text-dark"></div>
      <div class="text-dark fs-4"><span id="login-text" class="">Memuat... </span></div>
    </div>
    <div id="table-data" class="d-none table-responsive mt-3">
      <table class="table align-middle mb-0">
        <thead class="table-light">
         <tr>
            <th style="width: 5em">No</th>
            <th style="width: 10em">Nama Lengkap</th>
            <th style="width: 10em">Email</th>
            <th style="width: 5em" class="text-center">Aksi</th>
         </tr>
         </thead>
         <tbody>
          @php
              $index = 0
          @endphp
          @if (count($users)>0)
            @foreach ($users as $user)
              <tr>
                <td>{{++$index}}</td>
                <td>{{$user->customers->nama_lengkap}}</td>
                <td>{{$user->email}}</td>
                <td>
                  <div class="d-flex justify-content-center">
                    <div class="btn-group btn-group-sm">
                      <a type="button" class="btn btn-warning" style="color: white" href="{{route('customer.edit',$user->id)}}" data-toggle="tooltip" data-placement="top" title="Ubah" >Edit</a>
                      <button type="button" class="btn btn-danger delete-data" data-redirect="{{route('customer.destroy',$user->id)}}" data-id="{{ $user->id }}" data-token="{{ csrf_token() }}"> Hapus </button>
                    </div>
                  </div>
                </td>
            </tr>
            @endforeach
          @else
          <tr>
            <td class="text-center" colspan="6">Tidak Terdapat Data Customer</td>
         </tr>
          @endif
          </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-end">
      <nav aria-label="Page navigation example">
          {{$users->links('vendor.pagination.default')}}
        </nav>
    </div>
  </div>
</div>

@endsection

@section('js-content')
<script>
    $(document).ready(function () {
      function showLoadingIndicator() {
        $('#indikator-loading-data').removeClass('d-none');
      }

      function hideLoadingIndicator() {
        $('#indikator-loading-data').addClass('d-none');
        $('#table-data').removeClass('d-none')
      }
        fetchUserData();

        function fetchUserData() {
          showLoadingIndicator()

            $.ajax({
                url: "/panel/karyawan",
                type: 'GET',
                success: function (data) {
                    hideLoadingIndicator()
                },
                error: function () {
                    hideLoadingIndicator()
                }
            });
        }
    });
  </script>

@endsection